INSERT INTO TBL_CATEGORY (NAME) VALUES ('Familia');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Trabalho');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Faculdade');

INSERT INTO TBL_TAG (NAME) VALUES ('Importante');
INSERT INTO TBL_TAG (NAME) VALUES ('Ignorar');
INSERT INTO TBL_TAG (NAME) VALUES ('Bot');
INSERT INTO TBL_TAG (NAME) VALUES ('Loja');

INSERT INTO TBL_CONTACT (NAME, SURNAME, PHONE, EMAIL, NICKNAME, NOTE, CATEGORY_ID) VALUES
('John', 'Doe', 123456789, 'john.doe@example.com', 'Zé', 'Gente Boa', 2);
INSERT INTO TBL_CONTACT (NAME, SURNAME, PHONE, EMAIL, NICKNAME, NOTE, CATEGORY_ID) VALUES
('Jane', 'Doe', 987654321, 'jane.doe@example.com', 'Zá', 'Gente Legal', 1);
INSERT INTO TBL_CONTACT (NAME, SURNAME, PHONE, EMAIL, NICKNAME, NOTE, CATEGORY_ID) VALUES
('Vini', 'cius', 123123123, 'vini@example.com', 'Devi', 'Sou eu!', 1);

INSERT INTO TBL_CONTACT_TAG (CONTACT_ID, TAG_ID) VALUES (1, 1); -- John - Importante
INSERT INTO TBL_CONTACT_TAG (CONTACT_ID, TAG_ID) VALUES (1, 3); -- John - Bot
INSERT INTO TBL_CONTACT_TAG (CONTACT_ID, TAG_ID) VALUES (2, 2); -- Jane - Ignorar
INSERT INTO TBL_CONTACT_TAG (CONTACT_ID, TAG_ID) VALUES (2, 3); -- Jane - Bot
INSERT INTO TBL_CONTACT_TAG (CONTACT_ID, TAG_ID) VALUES (3, 4); -- Vini - Loja
